/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteAboutRouteImport } from './routes/_site.about'
import { Route as SiteAccountRouteImport } from './routes/_site.account'
import { Route as SiteBridalRouteImport } from './routes/_site.bridal'
import { Route as SiteCartRouteImport } from './routes/_site.cart'
import { Route as SiteCheckoutRouteImport } from './routes/_site.checkout'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteDressesRouteImport } from './routes/_site.dresses'
import { Route as SiteEthnicWearRouteImport } from './routes/_site.ethnic-wear'
import { Route as SiteFaqRouteImport } from './routes/_site.faq'
import { Route as SiteFestiveRouteImport } from './routes/_site.festive'
import { Route as SiteJeansRouteImport } from './routes/_site.jeans'
import { Route as SiteNewArrivalsRouteImport } from './routes/_site.new-arrivals'
import { Route as SiteOrderSuccessRouteImport } from './routes/_site.order-success'
import { Route as SitePrivacyRouteImport } from './routes/_site.privacy'
import { Route as SiteSaleRouteImport } from './routes/_site.sale'
import { Route as SiteSareesRouteImport } from './routes/_site.sarees'
import { Route as SiteShopRouteImport } from './routes/_site.shop'
import { Route as SiteTermsRouteImport } from './routes/_site.terms'
import { Route as SiteTopsRouteImport } from './routes/_site.tops'
import { Route as SiteWesternWearRouteImport } from './routes/_site.western-wear'
import { Route as SiteWishlistRouteImport } from './routes/_site.wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as SiteProductIdRouteImport } from './routes/_site.product.$id'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAccountRoute = SiteAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBridalRoute = SiteBridalRouteImport.update({
  id: '/bridal',
  path: '/bridal',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCartRoute = SiteCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCheckoutRoute = SiteCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDressesRoute = SiteDressesRouteImport.update({
  id: '/dresses',
  path: '/dresses',
  getParentRoute: () => SiteRoute,
} as any)
const SiteEthnicWearRoute = SiteEthnicWearRouteImport.update({
  id: '/ethnic-wear',
  path: '/ethnic-wear',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFaqRoute = SiteFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFestiveRoute = SiteFestiveRouteImport.update({
  id: '/festive',
  path: '/festive',
  getParentRoute: () => SiteRoute,
} as any)
const SiteJeansRoute = SiteJeansRouteImport.update({
  id: '/jeans',
  path: '/jeans',
  getParentRoute: () => SiteRoute,
} as any)
const SiteNewArrivalsRoute = SiteNewArrivalsRouteImport.update({
  id: '/new-arrivals',
  path: '/new-arrivals',
  getParentRoute: () => SiteRoute,
} as any)
const SiteOrderSuccessRoute = SiteOrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSaleRoute = SiteSaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSareesRoute = SiteSareesRouteImport.update({
  id: '/sarees',
  path: '/sarees',
  getParentRoute: () => SiteRoute,
} as any)
const SiteShopRoute = SiteShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTopsRoute = SiteTopsRouteImport.update({
  id: '/tops',
  path: '/tops',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWesternWearRoute = SiteWesternWearRouteImport.update({
  id: '/western-wear',
  path: '/western-wear',
  getParentRoute: () => SiteRoute,
} as any)
const SiteWishlistRoute = SiteWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteProductIdRoute = SiteProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => SiteRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRoute
  '/bridal': typeof SiteBridalRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/dresses': typeof SiteDressesRoute
  '/ethnic-wear': typeof SiteEthnicWearRoute
  '/faq': typeof SiteFaqRoute
  '/festive': typeof SiteFestiveRoute
  '/jeans': typeof SiteJeansRoute
  '/new-arrivals': typeof SiteNewArrivalsRoute
  '/order-success': typeof SiteOrderSuccessRoute
  '/privacy': typeof SitePrivacyRoute
  '/sale': typeof SiteSaleRoute
  '/sarees': typeof SiteSareesRoute
  '/shop': typeof SiteShopRoute
  '/terms': typeof SiteTermsRoute
  '/tops': typeof SiteTopsRoute
  '/western-wear': typeof SiteWesternWearRoute
  '/wishlist': typeof SiteWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/product/$id': typeof SiteProductIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/account': typeof SiteAccountRoute
  '/bridal': typeof SiteBridalRoute
  '/cart': typeof SiteCartRoute
  '/checkout': typeof SiteCheckoutRoute
  '/contact': typeof SiteContactRoute
  '/dresses': typeof SiteDressesRoute
  '/ethnic-wear': typeof SiteEthnicWearRoute
  '/faq': typeof SiteFaqRoute
  '/festive': typeof SiteFestiveRoute
  '/jeans': typeof SiteJeansRoute
  '/new-arrivals': typeof SiteNewArrivalsRoute
  '/order-success': typeof SiteOrderSuccessRoute
  '/privacy': typeof SitePrivacyRoute
  '/sale': typeof SiteSaleRoute
  '/sarees': typeof SiteSareesRoute
  '/shop': typeof SiteShopRoute
  '/terms': typeof SiteTermsRoute
  '/tops': typeof SiteTopsRoute
  '/western-wear': typeof SiteWesternWearRoute
  '/wishlist': typeof SiteWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/product/$id': typeof SiteProductIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/account': typeof SiteAccountRoute
  '/_site/bridal': typeof SiteBridalRoute
  '/_site/cart': typeof SiteCartRoute
  '/_site/checkout': typeof SiteCheckoutRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/dresses': typeof SiteDressesRoute
  '/_site/ethnic-wear': typeof SiteEthnicWearRoute
  '/_site/faq': typeof SiteFaqRoute
  '/_site/festive': typeof SiteFestiveRoute
  '/_site/jeans': typeof SiteJeansRoute
  '/_site/new-arrivals': typeof SiteNewArrivalsRoute
  '/_site/order-success': typeof SiteOrderSuccessRoute
  '/_site/privacy': typeof SitePrivacyRoute
  '/_site/sale': typeof SiteSaleRoute
  '/_site/sarees': typeof SiteSareesRoute
  '/_site/shop': typeof SiteShopRoute
  '/_site/terms': typeof SiteTermsRoute
  '/_site/tops': typeof SiteTopsRoute
  '/_site/western-wear': typeof SiteWesternWearRoute
  '/_site/wishlist': typeof SiteWishlistRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/product/$id': typeof SiteProductIdRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/bridal'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dresses'
    | '/ethnic-wear'
    | '/faq'
    | '/festive'
    | '/jeans'
    | '/new-arrivals'
    | '/order-success'
    | '/privacy'
    | '/sale'
    | '/sarees'
    | '/shop'
    | '/terms'
    | '/tops'
    | '/western-wear'
    | '/wishlist'
    | '/admin/login'
    | '/admin/products'
    | '/admin/'
    | '/product/$id'
    | '/admin/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/account'
    | '/bridal'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/dresses'
    | '/ethnic-wear'
    | '/faq'
    | '/festive'
    | '/jeans'
    | '/new-arrivals'
    | '/order-success'
    | '/privacy'
    | '/sale'
    | '/sarees'
    | '/shop'
    | '/terms'
    | '/tops'
    | '/western-wear'
    | '/wishlist'
    | '/admin/login'
    | '/admin/products'
    | '/'
    | '/admin'
    | '/product/$id'
    | '/admin/products/$id'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/account'
    | '/_site/bridal'
    | '/_site/cart'
    | '/_site/checkout'
    | '/_site/contact'
    | '/_site/dresses'
    | '/_site/ethnic-wear'
    | '/_site/faq'
    | '/_site/festive'
    | '/_site/jeans'
    | '/_site/new-arrivals'
    | '/_site/order-success'
    | '/_site/privacy'
    | '/_site/sale'
    | '/_site/sarees'
    | '/_site/shop'
    | '/_site/terms'
    | '/_site/tops'
    | '/_site/western-wear'
    | '/_site/wishlist'
    | '/admin/login'
    | '/admin/products'
    | '/_site/'
    | '/admin/'
    | '/_site/product/$id'
    | '/admin/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/account': {
      id: '/_site/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof SiteAccountRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/bridal': {
      id: '/_site/bridal'
      path: '/bridal'
      fullPath: '/bridal'
      preLoaderRoute: typeof SiteBridalRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/cart': {
      id: '/_site/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SiteCartRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/checkout': {
      id: '/_site/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof SiteCheckoutRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/dresses': {
      id: '/_site/dresses'
      path: '/dresses'
      fullPath: '/dresses'
      preLoaderRoute: typeof SiteDressesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ethnic-wear': {
      id: '/_site/ethnic-wear'
      path: '/ethnic-wear'
      fullPath: '/ethnic-wear'
      preLoaderRoute: typeof SiteEthnicWearRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/faq': {
      id: '/_site/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof SiteFaqRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/festive': {
      id: '/_site/festive'
      path: '/festive'
      fullPath: '/festive'
      preLoaderRoute: typeof SiteFestiveRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/jeans': {
      id: '/_site/jeans'
      path: '/jeans'
      fullPath: '/jeans'
      preLoaderRoute: typeof SiteJeansRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/new-arrivals': {
      id: '/_site/new-arrivals'
      path: '/new-arrivals'
      fullPath: '/new-arrivals'
      preLoaderRoute: typeof SiteNewArrivalsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/order-success': {
      id: '/_site/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof SiteOrderSuccessRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacy': {
      id: '/_site/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sale': {
      id: '/_site/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SiteSaleRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sarees': {
      id: '/_site/sarees'
      path: '/sarees'
      fullPath: '/sarees'
      preLoaderRoute: typeof SiteSareesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/shop': {
      id: '/_site/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof SiteShopRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/terms': {
      id: '/_site/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tops': {
      id: '/_site/tops'
      path: '/tops'
      fullPath: '/tops'
      preLoaderRoute: typeof SiteTopsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/western-wear': {
      id: '/_site/western-wear'
      path: '/western-wear'
      fullPath: '/western-wear'
      preLoaderRoute: typeof SiteWesternWearRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/wishlist': {
      id: '/_site/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof SiteWishlistRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/product/$id': {
      id: '/_site/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof SiteProductIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteAccountRoute: typeof SiteAccountRoute
  SiteBridalRoute: typeof SiteBridalRoute
  SiteCartRoute: typeof SiteCartRoute
  SiteCheckoutRoute: typeof SiteCheckoutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteDressesRoute: typeof SiteDressesRoute
  SiteEthnicWearRoute: typeof SiteEthnicWearRoute
  SiteFaqRoute: typeof SiteFaqRoute
  SiteFestiveRoute: typeof SiteFestiveRoute
  SiteJeansRoute: typeof SiteJeansRoute
  SiteNewArrivalsRoute: typeof SiteNewArrivalsRoute
  SiteOrderSuccessRoute: typeof SiteOrderSuccessRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteSaleRoute: typeof SiteSaleRoute
  SiteSareesRoute: typeof SiteSareesRoute
  SiteShopRoute: typeof SiteShopRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteTopsRoute: typeof SiteTopsRoute
  SiteWesternWearRoute: typeof SiteWesternWearRoute
  SiteWishlistRoute: typeof SiteWishlistRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteProductIdRoute: typeof SiteProductIdRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteAccountRoute: SiteAccountRoute,
  SiteBridalRoute: SiteBridalRoute,
  SiteCartRoute: SiteCartRoute,
  SiteCheckoutRoute: SiteCheckoutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteDressesRoute: SiteDressesRoute,
  SiteEthnicWearRoute: SiteEthnicWearRoute,
  SiteFaqRoute: SiteFaqRoute,
  SiteFestiveRoute: SiteFestiveRoute,
  SiteJeansRoute: SiteJeansRoute,
  SiteNewArrivalsRoute: SiteNewArrivalsRoute,
  SiteOrderSuccessRoute: SiteOrderSuccessRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteSaleRoute: SiteSaleRoute,
  SiteSareesRoute: SiteSareesRoute,
  SiteShopRoute: SiteShopRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteTopsRoute: SiteTopsRoute,
  SiteWesternWearRoute: SiteWesternWearRoute,
  SiteWishlistRoute: SiteWishlistRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteProductIdRoute: SiteProductIdRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
